/*
 * Generated by ISE 14.05.9.5220 GPL Edition - linux-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F256_6611();
extern void F258_6764();
extern void F263_6833();
extern void F264_6972();
extern void F287_3765();
extern void F280_6492();
extern void F199_4211();

extern void F199_4172(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE);
extern void F140_1792();
extern EIF_REFERENCE F140_1779();
extern EIF_BOOLEAN F140_1791();
extern EIF_BOOLEAN F140_1796();
extern void F140_1801();
extern void F140_1802();
extern void F140_1803();
extern void F74_1331();
extern EIF_TYPED_VALUE F74_1332();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F256_6611;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F263_6833;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F287_3765;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F258_6764;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F264_6972;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F280_6492;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 1;
	egc_init_scoop_manager = (void (*)(EIF_REFERENCE)) F199_4211;
	egc_scoop_manager_task_callback = F199_4172;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F140_1792;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F140_1791;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F140_1779;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F140_1796;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F140_1801;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F140_1802;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F140_1803;

	egc_str_dtype = 257;

	egc_str32_dtype = 263;
	egc_arr_dtype = 286;
	egc_tup_dtype = 211;
	egc_disp_rout_id = 3010;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)602;
	egc_sp_wchar = (EIF_TYPE_INDEX)816;
	egc_sp_bool = (EIF_TYPE_INDEX)428;
	egc_sp_uint8 = (EIF_TYPE_INDEX)744;
	egc_sp_uint16 = (EIF_TYPE_INDEX)711;
	egc_sp_uint32 = (EIF_TYPE_INDEX)638;
	egc_sp_uint64 = (EIF_TYPE_INDEX)481;
	egc_sp_int8 = (EIF_TYPE_INDEX)551;
	egc_sp_int16 = (EIF_TYPE_INDEX)783;
	egc_sp_int32 = (EIF_TYPE_INDEX)338;
	egc_sp_int64 = (EIF_TYPE_INDEX)451;
	egc_sp_real32 = (EIF_TYPE_INDEX)657;
	egc_sp_real64 = (EIF_TYPE_INDEX)355;
	egc_sp_pointer = (EIF_TYPE_INDEX)511;
	egc_sp_ref = (EIF_TYPE_INDEX)280;

	egc_uint8_dtype = 231;
	egc_uint16_dtype = 243;
	egc_uint32_dtype = 240;
	egc_uint64_dtype = 249;
	egc_int8_dtype = 213;
	egc_int16_dtype = 237;
	egc_int32_dtype = 246;
	egc_int64_dtype = 222;
	egc_bool_dtype = 225;
	egc_real32_dtype = 234;
	egc_char_dtype = 219;
	egc_wchar_dtype = 216;
	egc_real64_dtype = 228;
	egc_point_dtype = 252;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = 198;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 89;
	egc_except_emnger_dtype = 139;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "roboscoop_app";
	egc_system_location = "/home/mafilipp/catkin_ws/src/mafilipp/roboscoop/roboscoop_app/EIFGENs/roboscoop_app/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1412011264;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 910;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APP.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 5314;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 73;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F74_1331;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F74_1332;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 903; /* APP */
	}
}

#ifdef __cplusplus
}
#endif
